name: Test CI/CD Setup

on:
  push:
    branches: [ "main" ]

jobs:
  check-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "🎉 CI/CD pipeline is working successfully!"
